### ISSUE TITLE
Circularization and polishing stand alone script?

### ISSUE THREAD

**Issue by gwl2** [rotary-genomics/rotary#21]
Hi,
great workflow, will be a lot of help for people starting with ONT assembly!

This is more a feature request than reporting an issue.

Could your polishing of circular contigs be used without a the pipeline?
I think there might be quite some people that have their own workflows (like us ;-) that do more or less everything that is included in your pipeline. But the circularization and polishing, as carried out by rotary, is something unique that would be a very nice addition.
Do you have any plan to include the fix start of circlator (or is it already implemented?).

If it could work as a standalone script, it would be very easy to integrate into established workflows.

btw. how should your pipeline be cited in a paper?

Thanks a lot and kind regards!

**Comment by jmtsuji** [comment]
Thanks for trying out rotary in its beta state!

Indeed, a key unique feature of rotary is the "end polishing" step used to fix the ends of circular contigs assembled by Flye. In the future, I hope to make a proper CLI for rotary and to expose the end repair code as a standalone module.

For now, the end repair code is still in beta. Most of the code is in a Bash script ([flye_end_repair.sh](https://github.com/jmtsuji/rotary/blob/main/scripts/flye_end_repair.sh)) that works with some limitations (e.g., it might fail on circular DNA elements <100 kb). A supporting Python script ([flye_end_repair_utils.py](https://github.com/jmtsuji/rotary/blob/main/scripts/flye_end_repair_utils.py)) needs to be in the same folder as the Bash script for the code to run. If you want to use the end repair code in its current state as a standalone feature, you can do this hackily as follows:

(Run this code in the same folder as where you clone the `rotary` repo from Github)
```bash
# Install dependencies
conda env create -n end_repair rotary/envs/circlator.yaml
conda activate end_repair

# Run the end repair module
# Note: Replace [OPTIONS] below with any optional flags you want to add to the command.
#       Run `rotary/scripts/flye_end_repair.sh -h` for more details
#       The most important option is -f, where you set if the Flye assembly mode should be `nano-hq` (default) or `nano-raw`
rotary/scripts/flye_end_repair.sh [OPTIONS] longreads.fastq.gz assembly.fasta assembly_info.txt outdir
```

For more details, here is the help message from `rotary/scripts/flye_end_repair.sh`:
```
flye_end_repair.sh: pipeline to repair ends of circular contigs from Flye.
Copyright Jackson M. Tsuji, ILTS, Hokkaido University, 2022
Version: 0.1.0

Usage: flye_end_repair.sh [OPTIONS] longreads.fastq.gz assembly.fasta assembly_info.txt outdir

Positional arguments:
   longreads.fastq.gz:          QC-passing Nanopore reads
   assembly.fasta:              Contigs output from Flye
   assembly_info.txt:           Assembly info file from Flye
   outdir:                      Output directory path (might overwrite contents if the dir already exists!)

Optional arguments (general):
   -f flye_read_mode:           Type of input reads for Flye [nano-hq; can also set nano-raw]
   -F flye_read_error:          Expected error rate of input reads, expressed as proportion (e.g., 0.03) [0 = use flye defaults]
   -t threads:                  Number of processors to use [1]
   -m memory:                   Memory (GB) to use per thread for samtools sort [1]

Optional arguments (circlator merge module, used to stitch the reassembled ends to the original contigs):
   -i circlator_min_id:         Percent identity threshold for circlator merge [99]
   -l circlator_min_length:     Minimum required overlap (bp) between original and merge contigs [10000]
   -e circlator_ref_end:        Minimum distance (bp) between end of original contig and nucmer hit [100]
   -E circlator_reassemble_end: Minimum distance (bp) between end of merge contig and nucmer hit [100]
```
Sorry that I don't have anything more concrete at this point in terms of making the end repair workflow available as standalone code. My development work on rotary is more-or-less paused at the moment as I get oriented at a new research institute.

Regarding the other parts of the workflow you mentioned:
- Rotational polishing: this is a bit hard to summarize as its own module, because there are a lot of variables involved (e.g., do you have only long reads, or hybrid short/long reads? Which polishing tools do you want to use? etc.). If you want to implement polishing with rotation into your own workflow, the easiest way to do this is probably to polish the contigs once with a method of your choice, then rotate them (e.g., to the mid-point), then polish them again. You can rotate the contigs using `circlator fixstart` or several other methods.
- fixstart: yes, the `circlator fixstart` module is already implemented in the `rotary` workflow, at [step 7 in the workflow summary](https://github.com/jmtsuji/rotary/tree/develop#rotary-workflow-summary). :-)

Lastly, regarding citation: we recently posted a pre-print that describes rotary as part of a larger project. Feel free to cite this pre-print for now (I will add this to the README):
> JM Tsuji, NA Shaw, S Nagashima, JJ Venkiteswaran, SL Schiff, T Watanabe, M Fukui, S Hanada, M Tank, JD Neufeld (2023). Anoxygenic phototrophic _Chloroflexota_ member uses a Type I reaction center. _bioRxiv_, DOI:[10.1101/2020.07.07.190934](https://doi.org/10.1101/2020.07.07.190934) 

I hope this helps! Feel free to follow up if needed.

**Comment by LeeBergstrand** [comment]
End repair and circularization code is being moved to https://github.com/rotary-genomics/rotary-utils, a standalone application.
